# Generated by Django 4.2.27 on 2025-12-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TMDB', 'TMDb')], default='ADMIN', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
