# Generated by Django 4.2.27 on 2025-12-22 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG13', 'PG-13'), ('R', 'R'), ('NC17', 'NC-17')], default='PG13', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('source', models.CharField(choices=[('ADMIN', 'Admin'), ('TMDB', 'TMDb')], default='ADMIN', max_length=10)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('backdrop_path', models.CharField(blank=True, max_length=255)),
                ('original_language', models.CharField(blank=True, max_length=10)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'AUTHOR'}, related_name='authored_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieRatingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie')),
                ('spectator', models.ForeignKey(limit_choices_to={'role': 'SPECTATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='movie_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('spectator', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='movies.movie')),
                ('spectator', models.ForeignKey(limit_choices_to={'role': 'SPECTATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('spectator', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='AuthorRatingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'AUTHOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_as_author', to=settings.AUTH_USER_MODEL)),
                ('spectator', models.ForeignKey(limit_choices_to={'role': 'SPECTATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='author_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('spectator', 'author')},
            },
        ),
    ]
